# Site settings
title: AndrewBarna.org
email: me@andrewbarna.org
description: > # this means to ignore newlines until "baseurl:"
  Some say I do stuff... I'm probably at sea or something.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewbarna.org" # the base hostname & protocol for your site
twitter_username: AndrewBarna
github_username:  DocOtak

# Build settings
markdown: kramdown
